apiVersion: v1
kind: ConfigMap
metadata:
  name: manager-config
  labels:
    heritage: drycc
data:
data:
  init-clusters.json: |-
{{ toPrettyJson .Values.initClusters | indent 4}}
  xterm-pod-template.json: |-
{{ tpl (toPrettyJson .Values.xtermPodTemplate) $ | indent 4}}