apiVersion: v1
kind: Secret
metadata:
  name: manager-creds
  labels:
    heritage: drycc
data:
  {{- if (.Values.valkeyUrl) }}
  valkey-url: {{ .Values.valkeyUrl | b64enc }}
  {{- end }}
  {{- if (.Values.databaseReplicaUrl) }}
  database-replica-url: {{ .Values.databaseReplicaUrl | b64enc }}
  {{- end }}
  {{- if (.Values.passportUrl) }}
  passport-url: {{ .Values.passportUrl | b64enc }}
  {{- end }}
  {{- if (.Values.passportKey) }}
  passport-key: {{ .Values.passportKey | b64enc }}
  {{- end }}
  {{- if (.Values.passportSecret) }}
  passport-secret: {{ .Values.passportSecret | b64enc }}
  {{- end }}
  django-secret-key: {{ (include "common.secrets.lookup" (dict "secret" "manager-creds" "key" "django-secret-key" "defaultValue" (randAscii 64) "context" $)) }}
  stripe-public-key: {{ .Values.stripePublicKey | b64enc }}
  stripe-secret-key: {{ .Values.stripeSecretKey | b64enc }}
  stripe-webhook-secret: {{ .Values.stripeWebhookSecret | b64enc }}
