apiVersion: apps/v1
kind: Deployment
metadata:
  name: drycc-manager-celery
  labels:
    heritage: drycc
  annotations:
    component.drycc.cc/version: {{ .Values.imageTag }}
spec:
  replicas: {{ .Values.replicas }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: drycc-manager-celery
  template:
    metadata:
      labels: {{- include "common.labels.standard" . | nindent 8 }}
        app: drycc-manager-celery
    spec:
      affinity:
        podAffinity: {{- include "common.affinities.pods" (dict "type" .Values.celery.podAffinityPreset.type "component" "" "extraMatchLabels" .Values.celery.podAffinityPreset.extraMatchLabels "topologyKey" "" "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.celery.podAntiAffinityPreset.type "component" "" "extraMatchLabels" .Values.celery.podAntiAffinityPreset.extraMatchLabels "topologyKey" "" "context" $) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.celery.nodeAffinityPreset.type "key" .Values.celery.nodeAffinityPreset.key "values" .Values.celery.nodeAffinityPreset.values ) | nindent 10 }}
      serviceAccount: drycc-manager
      initContainers:
      - name: drycc-manager-celery-init
        image: {{.Values.imageRegistry}}/{{.Values.imageOrg}}/python-dev:latest
        imagePullPolicy: {{.Values.imagePullPolicy}}
        args:
        - netcat
        - -v
        - -u
        - $(DRYCC_DATABASE_URL),$(DRYCC_DATABASE_REPLICA_URL),$(DRYCC_VALKEY_URL),$(DRYCC_PASSPORT_URL)
        - -a
        - $(DRYCC_MANAGER_SERVICE_HOST):$(DRYCC_MANAGER_SERVICE_PORT)
        {{- include "manager.envs" . | indent 8 }}
        {{- include "manager.volumeMounts" . | indent 8 }}
      containers:
      - name: drycc-manager-celery
        image: {{.Values.imageRegistry}}/{{.Values.imageOrg}}/manager:{{.Values.imageTag}}
        imagePullPolicy: {{.Values.imagePullPolicy}}
        {{- if .Values.diagnosticMode.enabled }}
        command: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.command "context" $) | nindent 10 }}
        args: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.args "context" $) | nindent 10 }}
        {{- else }}
        args:
          - /bin/bash
          - -c
          - celery --app api worker --queues manager.low,manager.middle,manager.high --autoscale=32,1 --loglevel=WARNING
        {{- end }}
        {{- include "manager.limits" . | indent 8 }}
        {{- include "manager.envs" . | indent 8 }}
        {{- include "manager.volumeMounts" . | indent 8 }}
      {{- include "manager.volumes" . | indent 6 }}
