apiVersion: batch/v1
kind: CronJob
metadata:
  name: drycc-manager-cronjob-daily
  labels:
    heritage: drycc
  annotations:
    component.drycc.cc/version: {{ .Values.imageTag }}
spec:
  timeZone: "Etc/UTC"
  schedule: "0 1 * * *"
  concurrencyPolicy: {{ .Values.concurrencyPolicy }}
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          serviceAccount: drycc-manager
          initContainers:
          - name: drycc-manager-init
            image: {{.Values.imageRegistry}}/{{.Values.imageOrg}}/python-dev:latest
            imagePullPolicy: {{.Values.imagePullPolicy}}
            args:
            - netcat
            - -v
            - -u
            - $(DRYCC_DATABASE_URL),$(DRYCC_DATABASE_REPLICA_URL),$(DRYCC_VALKEY_URL),$(DRYCC_PASSPORT_URL)
            {{- include "manager.envs" . | indent 12 }}
            {{- include "manager.volumeMounts" . | indent 12 }}
          containers:
          - image: {{.Values.imageRegistry}}/{{.Values.imageOrg}}/manager:{{.Values.imageTag}}
            imagePullPolicy: {{.Values.imagePullPolicy}}
            name: drycc-manager-block-users
            {{- if .Values.diagnosticMode.enabled }}
            command: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.command "context" $) | nindent 14 }}
            args: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.args "context" $) | nindent 14 }}
            {{- else }}
            command:
              - /bin/bash
              - -c
            args:
              - python /workspace/manage.py block_users
            {{- end }}
            {{- include "manager.envs" . | indent 12 }}
            {{- include "manager.volumeMounts" . | indent 12 }}
          - image: {{.Values.imageRegistry}}/{{.Values.imageOrg}}/manager:{{.Values.imageTag}}
            imagePullPolicy: {{.Values.imagePullPolicy}}
            name: drycc-manager-clean-xterms
            {{- if .Values.diagnosticMode.enabled }}
            command: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.command "context" $) | nindent 14 }}
            args: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.args "context" $) | nindent 14 }}
            {{- else }}
            command:
              - /bin/bash
              - -c
            args:
              - python /workspace/manage.py clean_xterms
            {{- end }}
            {{- include "manager.limits" . | indent 12 }}
            {{- include "manager.envs" . | indent 12 }}
            {{- include "manager.volumeMounts" . | indent 12 }}
          - image: {{.Values.imageRegistry}}/{{.Values.imageOrg}}/manager:{{.Values.imageTag}}
            imagePullPolicy: {{.Values.imagePullPolicy}}
            name: drycc-manager-generate-bills
            {{- if .Values.diagnosticMode.enabled }}
            command: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.command "context" $) | nindent 14 }}
            args: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.args "context" $) | nindent 14 }}
            {{- else }}
            command:
              - /bin/bash
              - -c
            args:
              - python /workspace/manage.py generate_bills
            {{- end }}
            {{- include "manager.envs" . | indent 12 }}
            {{- include "manager.volumeMounts" . | indent 12 }}
          - image: {{.Values.imageRegistry}}/{{.Values.imageOrg}}/manager:{{.Values.imageTag}}
            imagePullPolicy: {{.Values.imagePullPolicy}}
            name: drycc-manager-generate-invoices
            {{- if .Values.diagnosticMode.enabled }}
            command: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.command "context" $) | nindent 14 }}
            args: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.args "context" $) | nindent 14 }}
            {{- else }}
            command:
              - /bin/bash
              - -c
            args:
              - python /workspace/manage.py generate_invoices
            {{- end }}
            {{- include "manager.envs" . | indent 12 }}
            {{- include "manager.volumeMounts" . | indent 12 }}
          {{- include "manager.volumes" . | indent 10 }}
