apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: manager-api-server
  labels:
    app: "manager"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  hostnames:
  - drycc-manager.{{ .Values.global.platformDomain }}
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: drycc-gateway
    sectionName: http
  {{- if .Values.global.certManagerEnabled }}
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: drycc-gateway
    sectionName: https
  {{- end }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: drycc-manager
      port: 80
