name: manager
apiVersion: v2
home: https://github.com/drycc/manager
dependencies:
  - name: common
    repository: oci://registry.drycc.cc/charts
    version: ~1.1.1
  - name: redis
    repository: oci://registry.drycc.cc/charts-testing
    version: x.x.x
  - name: database
    repository: oci://registry.drycc.cc/charts-testing
    version: x.x.x
  - name: rabbitmq
    repository: oci://registry.drycc.cc/charts-testing
    version: x.x.x
  - name: passport
    repository: oci://registry.drycc.cc/charts-testing
    version: x.x.x
description: Drycc Workflow Manager (API).
maintainers:
  - name: Drycc Team
    email: engineering@drycc.com
version: v1.0.0
