name: manager
apiVersion: v2
home: https://github.com/drycc/manager
dependencies:
- name: common
  repository: oci://registry.drycc.cc/charts
  version: ~1.1.2
- name: valkey
  repository: oci://registry.drycc.cc/charts
  version: x.x.x
  condition: valkey.enabled
- name: gateway
  repository: oci://registry.drycc.cc/charts
  version: x.x.x
  condition: gateway.enabled
- name: database
  repository: oci://registry.drycc.cc/charts
  version: x.x.x
  condition: database.enabled
- name: passport
  repository: oci://registry.drycc.cc/charts
  version: x.x.x
  condition: passport.enabled
description: Drycc Workflow Manager (API).
maintainers:
- name: Drycc Team
  email: engineering@drycc.com
version: v1.0.0
