# Generated by Django 2.2.14 on 2020-11-11 07:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('ingress', models.URLField(unique=True)),
                ('admin', models.CharField(max_length=64)),
                ('passwd', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
