# Generated by Django 2.2.14 on 2021-01-22 03:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementVolumes',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('app_id', models.CharField(db_index=True, max_length=63)),
                ('owner_id', models.CharField(db_index=True, max_length=63)),
                ('name', models.CharField(max_length=63)),
                ('size', models.IntegerField()),
                ('timestamp', models.FloatField(db_index=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Cluster')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MeasurementConfig',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('app_id', models.CharField(db_index=True, max_length=63)),
                ('owner_id', models.CharField(db_index=True, max_length=63)),
                ('container_type', models.CharField(max_length=63)),
                ('cpu', models.IntegerField()),
                ('memory', models.IntegerField()),
                ('timestamp', models.FloatField(db_index=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Cluster')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
