# Generated by Django 3.2.11 on 2022-05-08 09:53

import api.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='invoice_day',
            field=models.PositiveSmallIntegerField(default=api.utils.invoice_day, verbose_name='invoice day'),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'block'), (1, 'normal')], db_index=True, default=1, verbose_name='status'),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('price', models.PositiveBigIntegerField()),
                ('period', models.PositiveIntegerField(db_index=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'unsettled'), (1, 'unpaid'), (2, 'paid')], db_index=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
                'unique_together': {('owner', 'period')},
            },
        ),
    ]
