# Generated by Django 2.2.14 on 2021-03-18 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210318_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funding',
            name='operator',
            field=models.CharField(default='None', max_length=63),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='funding',
            name='trade_type',
            field=models.IntegerField(choices=[(1, 'expend'), (2, 'income')], db_index=True),
        ),
    ]
