# Generated by Django 2.2.14 on 2021-03-18 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210318_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funding',
            name='billing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.Bill'),
        ),
    ]
