# Generated by Django 3.2.11 on 2022-05-12 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220512_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentcard',
            name='other',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
