# Generated by Django 3.2.11 on 2022-05-16 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_paymentcard_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentcard',
            name='payment_provider',
            field=models.PositiveSmallIntegerField(choices=[(1, 'stripe')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentcard',
            name='other',
            field=models.TextField(blank=True),
        ),
    ]
