# Generated by Django 2.2.14 on 2021-03-18 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210318_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funding',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.Cluster'),
        ),
    ]
