# Generated by Django 3.2.11 on 2022-05-17 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20220516_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='prepaid',
            field=models.PositiveBigIntegerField(default=10000),
            preserve_default=False,
        ),
    ]
