# Generated by Django 2.2.18 on 2021-03-23 02:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210318_0642'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='config',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='instance',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='network',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='volume',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='bill',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bill',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bill',
            name='price_unit',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='resource',
            name='plan',
            field=models.CharField(max_length=128),
        ),
    ]
