# Generated by Django 2.2.18 on 2021-03-24 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210323_0240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funding',
            old_name='billing',
            new_name='bill',
        ),
    ]
