# Generated by Django 2.2.18 on 2021-03-30 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_message_is_deal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='user',
            new_name='owner',
        ),
    ]
