# Generated by Django 2.2.18 on 2021-05-25 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20210330_0827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cluster',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='cluster',
            name='passwd',
        ),
    ]
