# Generated by Django 4.2.8 on 2024-03-22 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20220526_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='type',
            field=models.CharField(max_length=64),
        ),
    ]
