# Generated by Django 2.2.18 on 2021-05-26 02:33

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20210525_0140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='price',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='price_unit',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='resource_type',
        ),
        migrations.AddField(
            model_name='bill',
            name='charge_rule_info',
            field=jsonfield.fields.JSONField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bill',
            name='resource_info',
            field=jsonfield.fields.JSONField(default={}),
            preserve_default=False,
        ),
    ]
