# Generated by Django 2.2.18 on 2021-05-26 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20210526_0234'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='resource_type',
            field=models.IntegerField(choices=[(1, 'cpu'), (2, 'memory'), (3, 'volume'), (4, 'network')], db_index=True, default=None),
            preserve_default=False,
        ),
    ]
