matrix:
  platform:
  - linux/amd64
  - linux/arm64

platform: ${platform}

labels:
  type: exec

pipeline:
- name: test-linux
  image: bash
  commands:
  - env
  - make test docker-build-test upload-coverage
  secrets:
  - dev_registry
  - codecov_token
  when:
    event:
    - push
    - tag
    - pull_request
